server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://122.112.141.60:3306/knowledge?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: haodong

swagger.enable: true

